version: "3"

services:

  Adminer1:
    image: adminer:latest
    container_name: adminer1
    ports:
      - "10001:8080"

  Adminer2:
    image: adminer:latest
    container_name: adminer2
    ports:
      - "10002:8080"

  Adminer3:
    image: adminer:latest
    container_name: adminer3
    ports:
      - "10003:8080"
