---
 - name: Install Docker
   hosts: UbuntuVM2
   become: yes

   vars: 
   - ansible_sudo_pass: alex
   - tmp_folder: /tmp/Docker # directory on remote host for store docker-compose.yml
   - tmp_folder_local: /TEST/ansible/NGINX_LB_ADMINER # directory on local host with docker-compose.yml
 
   tasks:
    - name: Update cache and install packages
      apt:
       name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip
       update_cache: yes
       state: latest

    - name: Add Docker GPG key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - "

#Получить релиз ubuntu для того чтобы скачать репозиторий

    - name: Get lsb_release
      shell: lsb_release -cs
      register: lsb_release

#добавляем docker репозитарий в список репозитарием ubuntu

    - name: Add docker repo
      ansible.builtin.apt_repository: 
         repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
         state: present

# Устанавливаем docker
    - name: Install Docker
      apt:
       name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
       state: latest	 

#Получить версию ОС
    - name: Get OS
      shell: uname -s
      register: os_version

#Получить архитектуру ОС
    - name: Get architecture
      shell: uname -m
      register: architecture

#Скачать docker compose
    - name: Download Docker-compose
      get_url: 
       url: "https://github.com/docker/compose/releases/download/1.28.0/docker-compose-{{ os_version.stdout }}-{{ architecture.stdout }}"
       dest: /usr/local/bin/docker-compose
       mode: 744

    - name: Enable Docker
      systemd:
          name: docker
          state: started

#Устанавливаем модули python через Pip
    - name: Pip install docker docker-compose
      pip:
       name: 
        - docker
        - docker-compose
